[tool.briefcase]
project_name = "CryptoApp"
bundle = "com.example"
formal_name = "CryptoApp"
author = "Your Name"
author_email = "your.email@example.com"
description = "A cryptocurrency application built with Kivy and BeeWare."
requires = ["kivy", "supabase", "reportlab", "bcrypt", "qrcode", "colorama"]
version = "0.1.0"

[tool.briefcase.app.crypto_app]
sources = ["crypto_app"]
license = "MIT"
