[tool.briefcase]
project_name = "VORTEX POCKET"
version = "1.0.0"
bundle = "com.example"
author = "MM"
author_email = "your.email@example.com"
description = "A short description of your project"
url = "https://example.com"
license = "MIT"

[tool.briefcase.app.your_project_name]
formal_name = "VORTEX POCKET"
description = "A short description of your project"
sources = ["src"]

[tool.briefcase.app.your_project_name.android]
# Android-specific settings
package = "com.example.yourprojectname"
